<div id="app">
    <div v-if="<?= $block->getBoolean() ? 'true' : 'false' ?>">
        <h2 class="text-center mb-4">Ingrese los datos de su tarjeta: </h2>
        <formulario url-guardar="<?= $block->getUrl('tareados/Index/save') ?>" :props-mostrar="<?= $block->getBoolean() ? 'true' : 'false' ?>"></formulario>
    </div>
    <div v-else>
        <div class="alert alert-warning" role="alert">
            Error
        </div>
        <img src="https://static.vecteezy.com/system/resources/previews/004/435/751/non_2x/404-error-page-with-black-cat-illustrations-not-found-system-updates-uploading-operation-computing-installation-programs-vector.jpg" ></img>
    </div>
    
</div>
<style>
    .card-cartao {
        display: flex;
        width: 736px;
        padding: 32px;
        flex-direction: row;
        align-items: flex-start;
        gap: 48px;
        flex-shrink: 0;
        background-color: #111827;
        margin: 0 auto;
        border-radius: 15px;
    }

    .column {
        flex: 1;
    }

    .row {
        display: flex;
        flex-direction: row;
        gap: 10px;
    }

    input[type="text"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 2px solid transparent;
        border-radius: 5px;
        background-color: #E5E7EB;
        color: #111827;
        transition: border-color 0.3s;
    }

    input[type="text"]:focus {
        border-color: #9333EA;
        outline: none;
    }

    label {
        color: white;
    }
    .btn-submit-c{
        width: 100%;
        height: 35px;
        border-radius: 8px;
    }
</style>