<?php 
$contactsCollection = $block->getContactosCollection();
?>
<div class="container">
    <h3>Contactos</h3>
    <table class="table table-striped mt-4">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Correo</th>
                <th scope="col">Teléfono</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($contactsCollection as $contacto) :?>
            <tr>
                <td><?= $contacto->getData()["id"] ?></td>
                <td><?= json_decode(json_encode($contacto->getData()))->nombre_completo ?></td>
                <td><?= $contacto->getData()["correo"] ?></td>
                <td><?= ((object)$contacto->getData())->telefono ?></td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>
