<div id="app" class="row">
    <div class="col-12 col-md-6">
        <div class="card tarjeta-producto">
            <div class="mx-auto">
                <img src="<?= $block->getApiResponse()->image ?>" alt="imagen de producto" class="card-img-top">
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="card tarjeta-producto">
            <div class="card-body">
                <h1 class="text-center"><?= $block->getApiResponse()->title ?></h1>
                <h5 class="card-text"><b>Category:</b> <?= $block->getApiResponse()->category ?></h5>
                <h5 class="card-text"><b>Price:</b> $<?= $block->getApiResponse()->price ?></h5>
                <h5 class="card-text"><b>Rating:</b> <?= $block->getApiResponse()->rating->rate ?> (<?= $block->getApiResponse()->rating->count ?> reviews)</h5>
                <button class="btn btn-primary btn-block">Add to Cart</button>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="card tarjeta-producto">
            <div class="card-body">
                <h5 class="card-text"><b>Description:</b></h5>
                <p class="card-text"><?= $block->getApiResponse()->description ?></p>
            </div>
        </div>
    </div>
</div>


<style>
    h1.text-center {
    font-size: 24px;
    margin-bottom: 20px;
    color: #333;
    }
    .card.tarjeta-producto {
    border: 1px solid #ccc;
    border-radius: 10px;
    margin-bottom: 20px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .card-img-top {
    max-width: 400px;
    height: auto;
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
    display: block;
    margin: 0 auto;
    }
    .card-body {
    padding: 20px;
    }
    .card-text {
    font-size: 18px;
    margin-bottom: 10px;
    }
    .btn-primary {
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    padding: 10px;
    font-size: 18px;
    cursor: pointer;
    transition: background-color 0.3s;
    }
    .btn-primary:hover {
    background-color: #0056b3;
    }
    .card-text.description {
    font-size: 16px;
    line-height: 1.5;
    }
</style>

